resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: git-pull-request
    type: pull-request
    source:
      uri: git@github.com:getoutreach/oauth2_proxy.git
      access_token: ((github-access-token))
      private_key: ((git-private-key))
      repo: getoutreach/oauth2_proxy
  - name: git-repo
    type: git
    source:
      uri: git@github.com:getoutreach/oauth2_proxy.git
      branch: master
      private_key: ((git-private-key))

jobs:
- name: test
  plan:
  - get: git-pull-requests
    trigger: true
    version: every
  - put: git-pull-requests
    params:
      path: git-pull-requests
      status: pending
  - task: test
    file: ci/test.yaml
    on_abort:
      put: git-pull-requests
      params:
        path: git-pull-requests
        status: failure
    on_failure:
      put: git-pull-requests
      params:
        path: git-pull-requests
        status: failure
  - put: git-pull-requests
    params:
      path: git-pull-requests
      status: success
