resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: pull-request
    type: pull-request
    source:
      uri: git@github.com:getoutreach/oauth2_proxy.git
      access_token: ((github-access-token))
      private_key: ((git-private-key))
      repo: getoutreach/oauth2_proxy

jobs:
- name: test-pr
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: pr-status-pending
    resource: pull-request
    params:
      path: pull-request
      status: pending
  - task: test
    file: pull-request/ci/test.yaml
    on_abort:
      put: pr-status-failed
      resource: pull-request
      params:
        path: pull-request
        status: failure
    on_failure:
      put: pr-status-failed
      resource: pull-request
      params:
        path: pull-request
        status: failure
  - put: pr-status-success
    resource: pull-request
    params:
      path: pull-request
      status: success
