resources:
  - name: git-repo
    type: git
    source:
      uri: git@github.com:getoutreach/oauth2_proxy.git
      branch: concourse_setup
      private_key: ((git-private-key))

jobs:
- name: hello-world
  plan:
  - get: git-repo
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
